Update build-padavan.yml

diff --git a/.github/workflows/build-padavan.yml b/.github/workflows/build-padavan.yml
--- a/.github/workflows/build-padavan.yml
+++ b/.github/workflows/build-padavan.yml
@@ -42,6 +42,11 @@ jobs:
         KERNEL: 3.4
       run: |
         cd /opt/rt-n56u/trunk
+        if [ ! -f configs/templates/$TNAME.config ] ; then
+        echo "configs/templates/$TNAME.config not found "
+        exit 1
+        fi
+        cp -f configs/templates/$TNAME.config .config
         ######################################################
         sed -i '/CONFIG_MTD_STORE_PART_SIZ/c\CONFIG_MTD_STORE_PART_SIZ=0x900000' configs/boards/PSG1218/kernel-3.4.x.config
         sed -i '/size_tmp="24M"/c\size_tmp="8M"' user/scripts/dev_init.sh
